/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grp.four.tk;

import grp.four.bk.Dag;
import grp.four.ktr.Koretoj;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Patrick
 */
public class TilfojKoretojerGUI extends javax.swing.JFrame {

    private TilknytKoretojHandler tilknytKoretojHandler;
    private TKGUI tKGUI;
    private Dag dag;

    /**
     * Creates new form TilfojKoretojerGUI
     */
    public TilfojKoretojerGUI(TilknytKoretojHandler tilknytKoretojHandler) {
        this.tilknytKoretojHandler = tilknytKoretojHandler;
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setDag(Dag dag) {
        this.dag = dag;
    }

    public void setTkGUI(TKGUI tKGUI) {
        this.tKGUI = tKGUI;
    }

    public void populerKoretojer() {
        DefaultListModel dlm = new DefaultListModel();
        ArrayList<Koretoj> koretojer = tilknytKoretojHandler.hentKoretojer();

        for (Koretoj k : koretojer) {
            if (k.getKategori().equals(dag.getKategori())) {
                if (!dag.getKoretojer().contains(k)) {
                    dlm.addElement(k.getFdmNo());
                }
            }
        }

        koretojer_LI.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        koretojer_LI = new javax.swing.JList();
        tilfoj = new javax.swing.JButton();
        annuller = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tilføj køretøjer");
        setResizable(false);

        jLabel1.setText("Marker køretøjer og tryk tilføj");

        jScrollPane1.setViewportView(koretojer_LI);

        tilfoj.setText("Tilføj");
        tilfoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilfojActionPerformed(evt);
            }
        });

        annuller.setText("Annuller");
        annuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tilfoj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(annuller)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tilfoj)
                    .addComponent(annuller))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullerActionPerformed
        dispose();
    }//GEN-LAST:event_annullerActionPerformed

    private void tilfojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilfojActionPerformed
        boolean success = tilknytKoretojHandler.tilfojKoretojTilDag(koretojer_LI.getSelectedValuesList(), dag.getDato());
        
        if(!success) {
            JOptionPane.showMessageDialog(this,
                    "Du må højest tilføje 6 køretøjer",
                    "FEJL",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            tKGUI.resetTilfojedeKoretojer();
            tKGUI.populerBookedeKurser();
            tKGUI.setCompStatus();
            dispose();
        }
    }//GEN-LAST:event_tilfojActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TilfojKoretojerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TilfojKoretojerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TilfojKoretojerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TilfojKoretojerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TilfojKoretojerGUI().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList koretojer_LI;
    private javax.swing.JButton tilfoj;
    // End of variables declaration//GEN-END:variables
}
