/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grp.four.bk;

import grp.four.klr.Korelaerer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Patrick
 */
public class BKGUI extends javax.swing.JFrame {

    /**
     * Creates new form BKGUI
     */
    private OpretDagsHandler dagsHandler;

    public BKGUI(OpretDagsHandler dagsHandler) {
        initComponents();
        this.dagsHandler = dagsHandler;
        setLocationRelativeTo(null);
        book.setEnabled(false);
        fjernElev.setEnabled(false);
    }

    public void resetGUI() {
        try {
            ledigDatoListe.setModel(new DefaultListModel());
            elevListe.setModel(new DefaultListModel());
        } catch (Exception e) {
        }
        dato.setText("Vælg dato");
        kategori.setModel(new DefaultComboBoxModel());
        korelaerer.setModel(new DefaultComboBoxModel());
        tilfojElev.setText("");
        dagsHandler.resetElever();
        book.setEnabled(false);
        fjernElev.setEnabled(false);
        dagsHandler.resetElever();
        tilfoj.setEnabled(true);
        tilfojElev.setEditable(true);
    }

    public void populerGUI() {
        populerKategorier();
        opdaterElevListe();
        opdaterDatoListe();
        opdaterKorelaererListe();
    }

    public void populerKategorier() {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        dcbm.addElement("A");
        dcbm.addElement("B");
        dcbm.addElement("C");
        dcbm.addElement("D");
        kategori.setModel(dcbm);
    }

    public void opdaterElevListe() {
        DefaultListModel dlm = new DefaultListModel();

        for (String s : dagsHandler.hentElever()) {
            dlm.addElement(s);
        }

        elevListe.setModel(dlm);
    }

    public void opdaterDatoListe() {
        DefaultListModel dlm = new DefaultListModel();

        for (String s : dagsHandler.startKursusBooking()) {
            dlm.addElement(s);
        }

        ledigDatoListe.setModel(dlm);
    }

    public void opdaterKorelaererListe() {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

        for (Korelaerer k : dagsHandler.hentKorelaerer()) {
            dcbm.addElement(k.getNavn());
        }

        korelaerer.setModel(dcbm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ledigDatoListe = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dato = new javax.swing.JTextField();
        kategori = new javax.swing.JComboBox();
        korelaerer = new javax.swing.JComboBox();
        tilfojElev = new javax.swing.JTextField();
        tilfoj = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        elevListe = new javax.swing.JList();
        fjernElev = new javax.swing.JButton();
        annuller = new javax.swing.JButton();
        book = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book kursus");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ledigDatoListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ledigDatoListe.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ledigDatoListeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ledigDatoListe);

        jLabel1.setText("Dato");

        jLabel2.setText("Kategori");

        jLabel3.setText("Kørelærer");

        jLabel4.setText("Tilføj elev");

        jLabel5.setText("Elever");

        dato.setEditable(false);
        dato.setText("Vælg dato");

        tilfoj.setText("Tilføj");
        tilfoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilfojActionPerformed(evt);
            }
        });

        elevListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(elevListe);

        fjernElev.setText("Fjern elev");
        fjernElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fjernElevActionPerformed(evt);
            }
        });

        annuller.setText("Annuller");
        annuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullerActionPerformed(evt);
            }
        });

        book.setText("Book");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dato)
                            .addComponent(kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(korelaerer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tilfojElev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tilfoj))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 176, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fjernElev, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(book)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(annuller)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(korelaerer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tilfojElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tilfoj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fjernElev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(annuller)
                            .addComponent(book))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullerActionPerformed
        dispose();
    }//GEN-LAST:event_annullerActionPerformed

    private void ledigDatoListeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ledigDatoListeValueChanged
        String selection = ledigDatoListe.getSelectedValue().toString();
        dato.setText(selection);
        book.setEnabled(true);
    }//GEN-LAST:event_ledigDatoListeValueChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        resetGUI();
    }//GEN-LAST:event_formWindowClosed

    private void tilfojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilfojActionPerformed
        String input = tilfojElev.getText();
        if (!input.isEmpty()) {
            dagsHandler.tilføjElev(input);
            tilfojElev.setText("");
            if (dagsHandler.elevListeEr6()) {
                tilfojElev.setEditable(false);
                tilfoj.setEnabled(false);
            }
            if (!dagsHandler.elevListeEr0()) {
                fjernElev.setEnabled(true);
            }
            opdaterElevListe();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Du skal skrive et navn i feltet",
                    "FEJL",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tilfojActionPerformed

    private void fjernElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fjernElevActionPerformed
        dagsHandler.fjernElev(elevListe.getSelectedValue().toString());
        if (!dagsHandler.elevListeEr6()) {
            tilfojElev.setEditable(true);
            tilfoj.setEnabled(true);
        }
        if (dagsHandler.elevListeEr0()) {
            fjernElev.setEnabled(false);
        }
        opdaterElevListe();
    }//GEN-LAST:event_fjernElevActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        if (dagsHandler.korerlaererKatalogEr0()) {
            JOptionPane.showMessageDialog(this,
                    "Du har ingen kørelærer registreret i systemet!",
                    "FEJL",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!dagsHandler.elevListeEr6()) {
            JOptionPane.showMessageDialog(this,
                    "Du SKAL have 6 elever for at kunne booke et kursus!",
                    "FEJL",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String[] elever = new String[dagsHandler.hentElever().size()];
            dagsHandler.hentElever().toArray(elever);
            dagsHandler.angivKursusOplysninger(dato.getText(), kategori.getSelectedItem().toString(), dagsHandler.hentKorelaerer(korelaerer.getSelectedItem().toString()), elever);
            resetGUI();
            populerGUI();
        }
    }//GEN-LAST:event_bookActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BKGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BKGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BKGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BKGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BKGUI().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuller;
    private javax.swing.JButton book;
    private javax.swing.JTextField dato;
    private javax.swing.JList elevListe;
    private javax.swing.JButton fjernElev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox kategori;
    private javax.swing.JComboBox korelaerer;
    private javax.swing.JList ledigDatoListe;
    private javax.swing.JButton tilfoj;
    private javax.swing.JTextField tilfojElev;
    // End of variables declaration//GEN-END:variables
}
